import type { SectionResult, ShowcaseData } from "../../types.js";
import { svgRect, svgText } from "../../svg/components.js";
import { ICONS, svgIcon } from "../../svg/icons.js";
import type { RenderContext } from "./context.js";

export function renderFooter(ctx: RenderContext, _data: ShowcaseData, y: number): SectionResult {
  const startY = y + 8;
  const parts: string[] = [];

  const label = "Generated by @eat-pray-ai/wingman";
  const labelW = label.length * 6.5; // approximate char width at size 11
  const labelX = ctx.cardWidth / 2;
  const iconX = labelX - labelW / 2 - 16;
  parts.push(svgIcon(iconX, startY + 5, ICONS.lightningCharge, { fill: ctx.colors.muted, size: 12 }));
  parts.push(
    svgText(labelX, startY + 16, label, {
      fill: ctx.colors.muted,
      size: 11,
      anchor: "middle",
    }),
  );

  return { svg: parts.join("\n"), height: startY + 30 - y };
}

export function renderEmpty(ctx: RenderContext, _data: ShowcaseData): string {
  const height = 120;
  const parts: string[] = [];
  parts.push(
    svgRect(0, 0, ctx.cardWidth, height, { fill: ctx.colors.bg, rx: 12, stroke: ctx.colors.border }),
  );
  parts.push(
    svgText(ctx.cardWidth / 2, 50, "Wingman Stats", {
      fill: ctx.colors.blue,
      size: 16,
      weight: "bold",
      anchor: "middle",
    }),
  );
  parts.push(
    svgText(ctx.cardWidth / 2, 80, "No activity in this period", {
      fill: ctx.colors.secondary,
      size: 14,
      anchor: "middle",
    }),
  );
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${ctx.cardWidth}" height="${height}" viewBox="0 0 ${ctx.cardWidth} ${height}">`,
    parts.join("\n"),
    `</svg>`,
  ].join("\n");
}
